AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
  ServiceName:
    Type: String
  Env:
    Type: String

Resources:
  DynamoDbTableUserProfiles:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Env}-${ProjectName}-user-profiles
      AttributeDefinitions:
        - AttributeName: email_address
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: email_address
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: !Sub ${Env}-${ProjectName}-index-username
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
