AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: ...

Parameters:
  ProjectName:
    Type: String
  ServiceName:
    Type: String
  Env:
    Type: String
  CodeBucket:
    Type: String
  CodeFile:
    Type: String

Resources:
  IamRoleLambda:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: Environment
          Value: !Ref Env

  IamPolicyCloudWatchLogs:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: IamPolicyCloudWatchLogs
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ServiceName}-${Env}:*
      Roles:
        - !Ref IamRoleLambda

  IamPolicyDynamoDbTableUsers:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: IamPolicyDynamoDbTableUsers
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:QueryItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Env}-${ProjectName}-user-profiles
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Env}-${ProjectName}-user-profiles/*
      Roles:
        - !Ref IamRoleLambda

  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-${Env}-user-change-event-handler
      Handler: user_change_event_handler.lambda_handler
      Architectures:
        - x86_64
      Runtime: python3.12
      CodeUri:
        Bucket: !Ref CodeBucket
        Key: !Ref CodeFile
      Role: !GetAtt IamRoleLambda.Arn
      MemorySize: 128
      Timeout: 15
      LoggingConfig:
        LogGroup: !Sub "/aws/lambda/${ServiceName}-${Env}"
      Environment:
        Variables:
          AWS_ACCOUNT_ID: !Sub "${AWS::AccountId}"
          ENV: !Ref Env
      Tags:
        ProjectName: !Ref ProjectName
        ServiceName: !Ref ServiceName
        Environment: !Ref Env

  SnsSubscriptionLambda:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-user-change-event-${Env}"
      Protocol: lambda
      Endpoint: !GetAtt Lambda.Arn

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Lambda
      Principal: sns.amazonaws.com
      SourceArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-user-change-event-${Env}"
