name: Build & Deploy

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure environment variables
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" = "develop" ]; then
            echo "ENV=dev" >> $GITHUB_ENV
          else
            echo "ENV=sandbox" >> $GITHUB_ENV
          fi

          BUILD_TIMESTAMP=$(date +%Y%m%d%H%M%S)
          LAMBDA_ARCHIVE_FILENAME="${{ github.event.repository.name }}-$BUILD_TIMESTAMP.zip"
          
          echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> $GITHUB_ENV
          echo "LAMBDA_ARCHIVE_FILENAME=$LAMBDA_ARCHIVE_FILENAME" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Lambda archive
        run: |
          cd src
          mkdir ../build
          zip -r "../build/$LAMBDA_ARCHIVE_FILENAME" .

      - name: Upload Lambda archive
        run: |
          aws --region="ap-southeast-2" s3 cp "build/$LAMBDA_ARCHIVE_FILENAME" "s3://bertybear-lambda-versions-$ENV/$LAMBDA_ARCHIVE_FILENAME"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy Cloudformation Stack
        run: |
          aws --region="ap-southeast-2" cloudformation deploy \
          --stack-name="${{ github.event.repository.name }}-${ENV}" \
          --template-file=".pipeline/cloudformation/template.yml" \
          --parameter-overrides \
          ProjectName="bertybear-smart-nursery" \
          ServiceName="${{ github.event.repository.name }}" \
          Env="$ENV"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: Deploy ApiGateway-Handler's Cloudformation Stack
        run: |
          aws --region="ap-southeast-2" cloudformation deploy \
          --stack-name="apig-${{ github.event.repository.name }}-${ENV}" \
          --template-file=".pipeline/cloudformation/apig-user-profile-handler.yml" \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
          ProjectName="bertybear-smart-nursery" \
          ServiceName="${{ github.event.repository.name }}" \
          Env="$ENV" \
          CodeBucket="bertybear-lambda-versions-$ENV" CodeFile="$LAMBDA_ARCHIVE_FILENAME"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy Sns-Handler's Cloudformation Stack
        run: |
          aws --region="ap-southeast-2" cloudformation deploy \
          --stack-name="sns-${{ github.event.repository.name }}-${ENV}" \
          --template-file=".pipeline/cloudformation/sns-user-profile-handler.yml" \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
          ProjectName="bertybear-smart-nursery" \
          ServiceName="${{ github.event.repository.name }}" \
          Env="$ENV" \
          CodeBucket="bertybear-lambda-versions-$ENV" CodeFile="$LAMBDA_ARCHIVE_FILENAME"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}